### ISSUE TITLE
Failed to activate the remember-session package

### ISSUE THREAD

**Issue by darrennolan** [hampustagerud/atom-remember-session#22]
1. Fresh install of Atom.
2. Installed remember-session from 'Install' settings view.
3. Crash happened.

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [remember-session](https://github.com/hampustagerud/atom-remember-session) package, v0.5.1

### Stack Trace

Failed to activate the remember-session package

```
At Cannot read property 'x' of undefined

TypeError: Cannot read property 'x' of undefined
  at restoreDimensions (C:\Users\Darren Nolan\.atom\packages\remember-session\lib\remember-session.coffee:70:4)
  at Object.module.exports.activate (C:\Users\Darren Nolan\.atom\packages\remember-session\lib\remember-session.coffee:8:7)
  at Package.module.exports.Package.activateNow (C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:240:19)
  at C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
  at C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Darren Nolan\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -0:26.2 core:backspace (atom-text-editor.editor.mini)
     -0:17.1 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
remember-session, v0.5.1

# Dev
No dev packages
```

**Comment by bmhkim** [comment]
I'm seeing this on OS X as well.

**Comment by SebastianBoyd** [comment]
Same problem

**Comment by toyosawa** [comment]
Same problem, Me too

**Comment by embik** [comment]
Same problem on Arch Linux (up-to-date) and Atom 0.187.0.

**Comment by bmhkim** [comment]
For those looking for a workaround to this issue, I've had good success with the save-session package (https://atom.io/packages/save-session).

**Comment by Evmorov** [comment]
Same problem, Lubuntu 14.10, almost fresh installing

**Comment by steelx** [comment]
same here

**Comment by Geen-Henk** [comment]
+1

**Comment by putrasurya** [comment]
+1 Windows 8.1 - Fresh Installing Atom 0.194.0

**Comment by mrz1836** [comment]
+1 Windows 8.1

**Comment by rubberbird** [comment]
+1

**Comment by ericrange** [comment]
+1

**Comment by jaitaiwan** [comment]
+1

**Comment by Andyroid1978** [comment]
+1
atom v. 0.208.0 on Kubuntu 15.04

**Comment by alazzawimahmoud** [comment]
+1

**Comment by denysdovhan** [comment]
Same problem

**Comment by jonzielen** [comment]
+1

**Comment by peonicles** [comment]
On windows, removing the folder `C:\Users\<username>\.atom` , then restarting atom works for me. This issue seems be caused by settings from a previous installation.

**Comment by serginator** [comment]
@peonicles that didn't worked for me :(

Atom 0.209.0 on Ubuntu 14.04

**Comment by denysdovhan** [comment]
Hey, guys, did you know that features [already include into Atom](https://github.com/atom/atom/issues/1603)? But then it didn't worked for Linux (Ubuntu, etc) and Windows. On v0.210.0 it works correctly: look at [#6466](https://github.com/atom/atom/issues/6466) and at [#7231](https://github.com/atom/atom/issues/7231) (in atom's repo).

Yesterday, I updated my Atom to v0.210.0 and after that this features works fine. So, try to update your editors.

**Comment by rhoconlinux** [comment]
Not working on linux (ubuntu 15.10) and atom 1.0.7
:(

**Comment by brettz9** [comment]
For me (in Windows), the error is `$ is not a function`

**Comment by darrennolan** [comment]
> THIS PACKAGE IS NOT BEING DEVELOPED ANYMORE AS THE ATOM EDITOR ITSELF NOW HAS THE SAME FUNCTIONALITY
